docs: More renames for wapi to vits
volueinsight/volue-insight-timeseries pull request #46
Opened 2023-11-21 11:00 UTC by deep-volue

2023-11-21 13:58 UTC, stigalvestad requested changes
Good! See my comment on the naming. 
Can you also correct the double https://https// here and include that in this PR?

2023-11-21 13:58 UTC, stigalvestad commented on docs/events.rst
> +VolueInsight Time-Series API supports listening for changes to curves.  An event listener is set up, and behaves
```suggestion
Volue Insight time series API supports listening for changes to curves.  An event listener is set up, and behaves
```

2023-11-21 14:13 UTC, deep-volue commented
> Good! See my comment on the naming. Can you also correct the double https://https// here:
> 
> https://github.com/volueinsight/volue-insight-timeseries/blob/610df35b2d57bbc5d3514f340d17e1e9676ef5ca/docs/quickstart.rst?plain=1#L65
> 
> and include that in this PR?

Yes, I removed that double https

2023-11-22 09:35 UTC, stigalvestad approved these changes
Great, this is good!

2023-11-22 09:37 UTC, merged